### ISSUE TITLE
Add attribution for music files

### ISSUE THREAD

**Issue by Jaykingamez** [Elijah-maker/GFM-Music-Submod#2]
I'm interested in finding out the sources for some of the music used. Too bad its hard to decipher with names like Battle 1 or Dictatorship 1.

Perhaps an additional text/csv file listing the sources of the song, song name, file name would be useful in that regard.

**Comment by Elijah-maker** [comment]
I actually don't know what it is either. Originally the submod was made by Jman, I asked him and he has no recollection of where he got most of the music. I tried labelling what I recognized and labelled everything I added, but some songs are still unclear.
